const COMMON = {
  SPLASH: 'splash',
  ONBOARDING: 'onboarding',
  FORGOTPASSWORD: 'forgotpassword',
  PASSCODE: 'passcode',
  NEWPASSWORD: 'newpassword',
  VERIIFYUSER: 'verifyuser',
  RESENDEMAIL: 'resendemail',
  RESETPASSWORD: 'resetpassword',
};

const AUTH = {
  LOGIN: 'login',
  LOGINFORM: 'loginform',
  HOME: 'home',
  DIRECTORY: 'directory',
  PLANS: 'plans',
  BOOKING: 'booking',
  CALENDARSCREEN: 'calendarscreen',
  ACCOUNT: 'account',
  ANNOUNCEMENTS: 'announcements',
  EMPLOYEE: 'employee',
  ANNOUNCEMENTSFORM: 'announcementsform',
  ADDEMPLOYEE: 'addemployee',
  VIEWEMPLOYEE: 'viewemployee',
  VIEWCOMPANY: 'viewcompany',
  ADDCOMPANY: 'addcompany',
  VIEWALLEMPLOYEEE: 'viewallemployee',
  SELECTPLAN: 'selectplan',
  ALLOCATIONS: 'allocations',
  ADDOWNER: 'addowner',
  ADDCEMPLOYEE: 'addcemployee',
  ONEEMPLOYEEE: 'oneemployee',
  CONGRATS: 'congrats',
  VISITORS: 'visitors',
  ADDVISITORS: 'addvisitors',
  SUPPORT: 'support',
  ADDTICKET: 'addticket',
  OPENTICKET: 'openticket',
  UPDATEEMPLOYEE: 'updateemployee',
  UPDATECOMPANY: 'updatecompany',
  EVENTS: 'events',
  ADDEEVENT: 'addevent',
  UPDATEEVENT: 'updateevent',
  PINEVENT: 'pinevent',
  ADDROOM: 'addroom',
  ADDATTENDEES: 'addattendees',
  PINVITED: 'pinvited',
  WEEK: 'week',
  SHARESCREEN: 'sharescreen',
  ADDTASK:'addtask',
};
export {COMMON, AUTH};
